
  name: zodiac_app
  description: A new Flutter project.

  publish_to: 'none' # Remove this line if you wish to publish to pub.dev

  version: 1.0.0+1

  environment:
    sdk: ">=2.19.0 <4.0.0"

  dependencies:
    flutter:
      sdk: flutter
    provider: ^6.0.5
    cupertino_icons: ^1.0.5

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^2.0.1

  flutter:
    uses-material-design: true